config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  devise_scope :user do
    resources :users, only: %i[index show]
  end

  resources :posts, only: %i[new create index]

  resources :likes, only: %i[create destroy]

  resources :friend_requests, only: %i[create destroy]
  resources :friendships, only: %i[create destroy]

  resources :notifications, only: %i[index destroy]

  resources :comments, only: %i[create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :friend, class_name: 'User'
  belongs_to :user

  validates_uniqueness_of :user, scope: :friend
  validate :cannot_have_received_request

  def cannot_have_received_request
    incoming_request = FriendRequest.where(user_id: friend_id, friend_id: user_id)

    errors.add(:user, "can't have a pending friend request") if incoming_request.any?
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend,
             class_name: 'User'

  validate :friend_request_present?, on: :accept_friend_request

  def friend_request_present?
    friend_request = FriendRequest.find_by(user_id: user, friend_id: friend)

    return unless friend_request.nil?

    errors.add :base,
               :friend_request_missing,
               message: 'associated friend request missing'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes
  has_many :liking_users,
           through: :likes,
           source: :user

  has_many :comments
  has_many :commenting_users,
           through: :comments,
           source: :user

  scope :user_and_friends, ->(user) { where(user_id: [[user.id] + user.friend_ids]) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friend_requests
  has_many :friendships
  has_many :friends,
           through: :friendships

  has_many :likes
  has_many :liked_posts,
           through: :likes,
           source: :post

  has_many :notifications

  has_many :posts

  has_many :comments
  has_many :commented_posts,
           through: :comments,
           source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)

    if comment.save
      flash[:notice] = 'Added comment.'
    else
      flash[:alert] = 'Unable to add comment.'
    end

    redirect_back_or_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  around_action :complete_friendship, only: :create
  around_action :destroy_friendship, only: :destroy

  def create
    user = User.find_by(id: params[:user])
    friendship = user.friendships.build(friend_id: params[:friend])

    friendship.save!(context: :accept_friend_request)

    redirect_back_or_to root_path
  end

  def destroy
    friendship = Friendship.find_sole_by(id: params[:id])

    friendship.destroy!

    redirect_back_or_to root_path
  end

  def destroy_inverse_friendship
    inverse_friendship = Friendship.find_sole_by(user_id: params[:friend], friend_id: params[:user])

    inverse_friendship.destroy!
  end

  def add_friend_back
    friend = User.find_by(id: params[:friend])
    inverse_friendship = friend.friendships.build(friend_id: params[:user])

    inverse_friendship.save!
  end

  def delete_associated_request
    friend_request = FriendRequest.find_by(friend_id: params[:friend], user_id: params[:user])

    friend_request.destroy!
  end

  def notify_friend
    user = User.find_by(id: params[:user])
    friend = User.find_by(id: params[:friend])

    friend.notifications.create!(description:
                                 '<span class="notification_username">'\
                                 "#{user.email}"\
                                 '</span>'\
                                 ' accepted your friend request! You are now friends!')
  end

  def complete_friendship
    ActiveRecord::Base.transaction do
      yield
      add_friend_back
      delete_associated_request
      notify_friend
    end
  rescue ActiveRecord::RecordInvalid
    flash[:alert] = 'Unable to add friend.'
    redirect_back_or_to root_path
  end

  def destroy_friendship
    ActiveRecord::Base.transaction do
      yield
      destroy_inverse_friendship
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find_by(id: params[:post])
    user = User.find_by(id: params[:user])

    like = Like.new(post:, user:)

    if like.save
      flash[:notice] = 'Liked the post!'
    else
      flash[:alert] = 'Unable to like post.'
    end

    redirect_to root_path
  end

  def destroy
    like = Like.find(params[:id])

    if like.destroy
      flash[:notice] = 'Unliked post.'
    else
      flash[:alert] = 'Unable to dislike post.'
    end

    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.user_and_friends(current_user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = 'Successfully created new post.'
      redirect_to root_path
    else
      flash[:alert] = 'Unable to create post.'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    friend_requests = current_user.friend_requests

    @users = User.all
    @friend_requester_ids = friend_requests.pluck(:friend_id)
    @friend_ids = current_user.friend_ids
    @friend_request_recipient_ids = FriendRequest.all.where(friend_id: current_user.id).pluck(:user_id)
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<%= link_to 'Create new post', new_post_path %>

<ul>
<% @posts.each do |post| %>
  <li>
    <%= post.user.email %>
    <%= post.content %>
    <% if post.liking_users.include?(current_user) %>
      <% like = Like.find_by(post:, user: current_user) %>
      <%= button_to 'Unlike', like_path(like), method: :delete %>
    <% else %>
      <%= button_to 'Like', likes_path, params: { post:, user: current_user } %>
    <% end %>
    <p>
    Liked by
    <% post.liking_users.each do |user| %>
      <%= user.email %>
    <% end %>
    </p>

    <%= form_with model: Comment.new do |form| %>
      <%= hidden_field_tag 'comment[post_id]', post.id %>
      <%= form.text_field :content %>
      <%= form.submit %>
    <% end %>

    <ul>
      <% post.comments.each do |comment| %>
        <li><%= comment.user.email %> <%= comment.content %></li>
      <% end %>
    </ul>
  </li>
<% end %>
</ul>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <%= form.text_area :content %>
  <%= form.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<ul>
  <% @users.each do |user| %>
    <% next if current_user.id == user.id %>

    <li>
      <% if @friend_requester_ids.include?(user.id) %>
        <% friend_request = FriendRequest.find_sole_by(user_id: current_user, friend_id: user) %>

        <%= user.email %>
        <%= button_to 'Accept Friend Request', friendships_path, params: { user: current_user, friend: user } %>
        <%= button_to 'Decline Friend Request', friend_request_path(friend_request), params: { user: current_user, friend: user }, method: :delete %>
      <% elsif @friend_ids.include?(user.id) %>
        <% friendship = Friendship.find_sole_by(user_id: current_user, friend_id: user) %>
        <%= user.email %>
        <%= button_to 'Unfriend', friendship_path(friendship), params: { user: current_user, friend: user }, method: :delete %>
      <% elsif @friend_request_recipient_ids.include?(user.id) %>
        <% friend_request = FriendRequest.find_sole_by(user_id: user, friend_id: current_user) %>

        <%= button_to 'Cancel Friend Request', friend_request_path(friend_request), params: { user: user, friend: current_user }, method: :delete %>
      <% else %>
        <%= user.email %><%= button_to 'Send Friend Request', friend_requests_path, params: { user:, friend: current_user } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>